name: Build and Deploy
on:
  push:
    branches:
      - '*/main'

jobs:
  build-and-deploy:
    env:
      BRANCH_PREFIX: $(cat gradle.properties | grep mod_version | cut -d'+' -f2)
    strategy:
      matrix:
        java: [
          17,
        ]
    runs-on: ubuntu-latest
    steps:
      - name: check environment variables
        run: env
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        if: github.ref == 'refs/heads/${{ env.BRANCH_PREFIX }}/main'
        run: ./gradlew build
      - name: capture build artifacts
        if: |
          ${{ matrix.java == '17' }}
          github.ref == 'refs/heads/${{ env.BRANCH_PREFIX }}/main'
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/
      - name: get mod version
        if: github.ref == 'refs/heads/${{ env.BRANCH_PREFIX }}/main'
        id: mod_version
        run: |
          mod_version_val=$(grep "mod_version" gradle.properties | cut -d'=' -f2 | tr -d '\n')
          echo "mod_version=$mod_version_val" >> $GITHUB_OUTPUT
      - name: get minecraft version
        if: github.ref == 'refs/heads/${{ env.BRANCH_PREFIX }}/main'
        id: minecraft_version
        run: |
          minecraft_version_val=$(grep "mod_version" gradle.properties | cut -d'+' -f2 | tr -d '\n')
          echo "minecraft_version=$minecraft_version_val" >> $GITHUB_OUTPUT
      - name: deploy with mc-publish
        if: github.ref == 'refs/heads/${{ env.BRANCH_PREFIX }}/main'
        uses: Kir-Antipov/mc-publish@v2.1
        with:
          #curseforge-id: 514734
          #curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          #curseforge-dependencies: |
          #  fabric-api | depends | *
          #curseforge-files-secondary: build/libs/*-@(sources\|javadoc).jar

          modrinth-id: wFyCClLQ
          modrinth-token: "${{ secrets.MODRINTH_TOKEN }}"
          modrinth-dependencies: |
            fabric-api | depends | *
          modrinth-files-primary: build/libs/!(*-@(sources|javadoc)).jar
          # Modrinth has issues accepting javadocs right now
          modrinth-files-secondary: build/libs/*-sources.jar

          # github-tag: "${{ steps.mod_version.outputs.mod_version }}"
          # github-token: ${{ secrets.REPOSITORY_TOKEN }}
          # github-commitish: ${{ steps.minecraft_version.outputs.minecraft_version }}/main
          # github-files-secondary: build/libs/*-@(sources\|javadoc).jar

          version: "${{ steps.mod_version.outputs.mod_version }}"
          version-type: release
          changelog-file: CHANGELOG.md

          loaders: fabric
          game-versions: "${{ steps.minecraft_version.outputs.minecraft_version }}"
          java: "${{ matrix.java }}"